### ISSUE TITLE
Limit number of active devices

### ISSUE THREAD

**Issue by linted** [linted/HardwareCheckout#105]
Limit the number of active sessions for a user to 1. Right now a user can register for multiple queues and get multiple devices, thus limiting the number of active users. We need a way to allow a user to enter multiple queues, since one queue might be considerably longer then another, but only have one device at a time. My thoughts were to prompt the user to see if they wish to give up their current device and take the next one, or pass on taking the new device.

**Comment by MattBrownCA** [comment]
What if the user gets passed up in the queue when already using a device but does not lose their place in the queue. So when they give up their current device they have the opportunity to get the next device.

**Comment by linted** [comment]
Fixed.
