### ISSUE TITLE
Single entry listed multiple times on the front page.

### ISSUE THREAD

**Issue by linted** [linted/HardwareCheckout#115]
Happens when coming from refresh not from web socket.

**Comment by 5hu5ky** [comment]
Tried to replicate with soft and hard refresh on Chrome and FF cannot replicate. Please provide more details.

**Comment by linted** [comment]
I think that the issues lies with the fact that the front page is displaying all devices owned by the user, and the websocket is trying to display the device owned by the user which results in multiple copies of the device showing up. Testing  a fix.

**Comment by linted** [comment]
![Screenshot_2020-07-26_13-14-31](https://user-images.githubusercontent.com/10934700/88485187-03fe2580-cf42-11ea-93e8-15a7381a41a7.png)

**Comment by linted** [comment]
This should be fixed with #131

**Comment by 5hu5ky** [comment]
Closing the issue...
