### ISSUE TITLE
weird banner on first HTTPS shell

### ISSUE THREAD

**Issue by BenGardiner** [linted/HardwareCheckout#117]
![image](https://user-images.githubusercontent.com/243321/87826125-4fc81500-c846-11ea-8b7a-c8c07e0ffc49.png)

not really sure why it looks cool on re-login but crappy on first login. But trimming the indent a bit should help

**Comment by linted** [comment]
It has to do with the terminal size. if the terminal is less then 86 characters wide (the default is 80 on most machines) then the ascii art is distorted. I think the easiest solution would be to remove some of the padding at the begining of the art to limit it to 80 characters per line. A more difficult solution would be to dynamically determine the terminal size and add padding based on that
